/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package registration_form_tests;

import org.junit.jupiter.api.Test;

import static com.codeborne.*;

import static org.junit.jupiter.api.Assertions.*;

public class RegistrationFormTests {

    @Test
    void successAllRegistrationFormFieldsPopulation() {
        open("https://demoqa.com/automation-practice-form");
        $("input[id=firstName]").setValue("Jane");
        $("input[id=lastName]").setValue("Smith");
        $("input[id=userEmail]").setValue("janesmith@mail.com");
        $("input[value=Female]").click();
    }
}
