/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package registration_form_tests;

import org.junit.jupiter.api.Test;
import registration_form_tests.App;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
